/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef CRYSTALSERVER_PRIVATE_H
#define CRYSTALSERVER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.0.0"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	"1.0"
#define FILE_DESCRIPTION	"The Crystal Server"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"crystalserver.exe"
#define PRODUCT_NAME	"The Crystal Server"
#define PRODUCT_VERSION	"1.0"

#endif /*CRYSTALSERVER_PRIVATE_H*/
